RelivMVC/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RelivMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace RelivMVC.Controllers
{
    public class CategoriaController : Controller
    {
        Uri baseAdrees = new Uri("https://localhost:7186/api");
        private readonly HttpClient _client;

        public CategoriaController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAdrees;
        }

        public IActionResult Index()
        {
            List<CategoriaViewModel> lista = new List<CategoriaViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Categoria/GetCategorias").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var apiResponse = JsonConvert.DeserializeObject<ApiResponse<List<CategoriaViewModel>>>(data);
                lista = apiResponse?.Data ?? new List<CategoriaViewModel>();
            }

            return View(lista);
        }

        [HttpPost()]
        public IActionResult Create([FromBody] CategoriaViewModel categoriaViewModel)
        {
            if (categoriaViewModel == null || string.IsNullOrWhiteSpace(categoriaViewModel.Descripcion))
            {
                return Json(new { success = false, errorMessage = "Datos inválidos." });
            }

            HttpResponseMessage response = _client.PostAsJsonAsync(_client.BaseAddress + "/Categoria/PostCategoria", categoriaViewModel).Result;

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }

            string errorContent = response.Content.ReadAsStringAsync().Result;
            Console.WriteLine("Error de la API: " + errorContent);
            return Json(new { success = false, errorMessage = "La categoría no pudo ser creado." });
        }

        [HttpPut()]
        public IActionResult Put(int id, [FromBody] CategoriaViewModel categoria)
        {
            if (ModelState.IsValid)
            {
                var jsonContent = new StringContent(JsonConvert.SerializeObject(categoria), Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync($"{_client.BaseAddress}/Categoria/PutCategoria/{id}", jsonContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    return Json(new { success = true });
                }
                else
                {
                    ModelState.AddModelError("", "Error al actualizar el estado");
                }
            }
            return View(categoria);
        }

        [HttpDelete()]
        public IActionResult Delete(int id)
        {
            HttpResponseMessage response = _client.DeleteAsync($"{_client.BaseAddress}/Categoria/DeleteCategoria/{id}").Result;

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }
            else
            {
                ModelState.AddModelError("", "Error al eliminar la categoria");
                return RedirectToAction("Index");
            }
        }

    }
}

RelivMVC/Controllers/EstadoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RelivMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace RelivMVC.Controllers
{
    public class EstadoController : Controller
    {
        Uri baseAdrees = new Uri("https://localhost:7186/api");
        private readonly HttpClient _client;

        public EstadoController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAdrees;
        }

        public IActionResult Index()
        {
            List<EstadoViewModel> lista = new List<EstadoViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Estado/GetEstados").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var apiResponse = JsonConvert.DeserializeObject<ApiResponse<List<EstadoViewModel>>>(data);
                lista = apiResponse?.Data ?? new List<EstadoViewModel>();
            }

            return View(lista);
        }

        [HttpPost()]
        public IActionResult Create([FromBody] EstadoViewModel estadoViewModel)
        {
            if (estadoViewModel == null || string.IsNullOrWhiteSpace(estadoViewModel.Descripcion))
            {
                return Json(new { success = false, errorMessage = "Datos inválidos." });
            }

            HttpResponseMessage response = _client.PostAsJsonAsync(_client.BaseAddress + "/Estado/PostEstados", estadoViewModel).Result;

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }

            string errorContent = response.Content.ReadAsStringAsync().Result;
            Console.WriteLine("Error de la API: " + errorContent);
            return Json(new { success = false, errorMessage = "El estado no pudo ser creado." });
        }

        [HttpPut()]
        public IActionResult Put(int id, [FromBody] EstadoViewModel estado)
        {
            if (ModelState.IsValid)
            {
                var jsonContent = new StringContent(JsonConvert.SerializeObject(estado), Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync($"{_client.BaseAddress}/Estado/PutEstado/{id}", jsonContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    return Json(new { success = true });
                }
                else
                {
                    ModelState.AddModelError("", "Error al actualizar el estado");
                }
            }
            return View(estado);
        }

        [HttpDelete()]
        public IActionResult Delete(int id)
        {
            HttpResponseMessage response = _client.DeleteAsync($"{_client.BaseAddress}/Estado/DeleteEstado/{id}").Result;

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }
            else
            {
                ModelState.AddModelError("", "Error al eliminar el estado");
                return RedirectToAction("Index");
            }
        }

    }
}

RelivMVC/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RelivMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace RelivMVC.Controllers
{
    public class ProductoController : Controller
    {
        Uri baseAdrees = new Uri("https://localhost:7186/api");
        private readonly HttpClient _client;

        public ProductoController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAdrees;
        }

        public IActionResult Index()
        {
            List<ProductoViewModel> lista = new List<ProductoViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Producto/GetProductos").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var apiResponse = JsonConvert.DeserializeObject<ApiResponse<List<ProductoViewModel>>>(data);
                lista = apiResponse?.Data ?? new List<ProductoViewModel>();
            }

            return View(lista);
        }

        [HttpGet("GetCategorias")]
        public IActionResult GetCategorias()
        {
            List<CategoriaViewModel> lista = new List<CategoriaViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Categoria/GetCategorias").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var apiResponse = JsonConvert.DeserializeObject<ApiResponse<List<CategoriaViewModel>>>(data);
                lista = apiResponse?.Data ?? new List<CategoriaViewModel>();
            }
            return View(lista); 
        }

        [HttpGet("GetEstados")]
        public IActionResult GetEstados()
        {
            List<EstadoViewModel> lista = new List<EstadoViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Estado/GetEstados").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var apiResponse = JsonConvert.DeserializeObject<ApiResponse<List<EstadoViewModel>>>(data);
                lista = apiResponse?.Data ?? new List<EstadoViewModel>();
            }
            return View(lista);
        }



        [HttpPost]
        public IActionResult Create([FromBody] ProductoViewModel productoViewModel)
        {

            if (productoViewModel == null || string.IsNullOrWhiteSpace(productoViewModel.Nombre) || productoViewModel.Precio <= 0 || productoViewModel.Stock <= 0)
            {
                return Json(new { success = false, errorMessage = "Datos inválidos." });
            }

            HttpResponseMessage response = _client.PostAsJsonAsync(_client.BaseAddress + "/Producto/PostProducto", productoViewModel).Result;

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }

            string errorContent = response.Content.ReadAsStringAsync().Result;
            Console.WriteLine("Error de la API: " + errorContent);
            return Json(new { success = false, errorMessage = "El producto no pudo ser creado." });
        }

        [HttpPut()]
        public IActionResult Put(int id, [FromBody] ProductoViewModel producto)
        {
            if (ModelState.IsValid)
            {
                var jsonContent = new StringContent(JsonConvert.SerializeObject(producto), Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync($"{_client.BaseAddress}/Producto/PutProducto/{id}", jsonContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    return Json(new { success = true });
                }
                else
                {
                    ModelState.AddModelError("", "Error al actualizar el producto");
                }
            }
            return View(producto);
        }

        [HttpDelete()]
        public IActionResult Delete(int id)
        {
            HttpResponseMessage response = _client.DeleteAsync($"{_client.BaseAddress}/Producto/DeleteProducto/{id}").Result;

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true });
            }
            else
            {
                ModelState.AddModelError("", "Error al eliminar el producto");
                return RedirectToAction("Index");
            }
        }
    }
    }

RelivMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RelivMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RelivMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estado" asp-action="Index">Estados</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RelivMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>